"""empty message

Revision ID: 07329fd18979
Revises: 15a715b5efe6
Create Date: 2024-06-15 20:20:19.481741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07329fd18979'
down_revision = '15a715b5efe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievment_id'], ['achievment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_achievments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievments_achievment_id'), ['achievment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievments_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievments_achievment_id'))

    op.drop_table('user_achievments')
    op.drop_table('achievment')
    # ### end Alembic commands ###
