"""empty message

Revision ID: 228b421ded5e
Revises: 
Create Date: 2024-06-13 20:18:58.640982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '228b421ded5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=80), server_default='user', nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=4096), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_time'), ['time'], unique=False)

    op.create_table('trainer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sports', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('about', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainer_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainer_profile_user_id'), ['user_id'], unique=False)

    op.create_table('trainer_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_user_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['trainer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainer_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainer_review_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainer_review_trainer_user_id'), ['trainer_user_id'], unique=False)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_user_id'), ['user_id'], unique=False)

    op.create_table('user_to_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_to_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_to_chat_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_to_chat_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_to_chat_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_to_chat_chat_id'))

    op.drop_table('user_to_chat')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_user_id'))

    op.drop_table('user_profile')
    with op.batch_alter_table('trainer_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainer_review_trainer_user_id'))
        batch_op.drop_index(batch_op.f('ix_trainer_review_author_user_id'))

    op.drop_table('trainer_review')
    with op.batch_alter_table('trainer_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainer_profile_user_id'))

    op.drop_table('trainer_profile')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_time'))
        batch_op.drop_index(batch_op.f('ix_message_sender'))
        batch_op.drop_index(batch_op.f('ix_message_chat_id'))

    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('image')
    op.drop_table('chat')
    # ### end Alembic commands ###
