"""empty message

Revision ID: b9b80256ed07
Revises: 
Create Date: 2024-06-09 16:46:34.603312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b80256ed07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=1024), server_default='https://hb.bizmrg.com/st.cityfootball.ru/player/147521/photo/6330540f23d81_295x295.jpg', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_time'), ['time'], unique=False)

    op.create_table('user_to_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_to_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_to_chat_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_to_chat_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_to_chat_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_to_chat_chat_id'))

    op.drop_table('user_to_chat')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_time'))
        batch_op.drop_index(batch_op.f('ix_message_sender'))
        batch_op.drop_index(batch_op.f('ix_message_chat_id'))

    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('chat')
    # ### end Alembic commands ###
