"""empty message

Revision ID: f0e68e3d0adf
Revises: a20ece613f3b
Create Date: 2024-06-15 14:50:35.245085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e68e3d0adf'
down_revision = 'a20ece613f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('zoom_link', sa.String(length=4096), nullable=True),
    sa.Column('time_start', sa.Integer(), nullable=False),
    sa.Column('time_finish', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_time_finish'), ['time_finish'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_time_start'), ['time_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_trainer_user_id'), ['trainer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_trainer_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_time_start'))
        batch_op.drop_index(batch_op.f('ix_workout_time_finish'))

    op.drop_table('workout')
    # ### end Alembic commands ###
